name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liiDZ2DP9q81kwy7"
GITHUB_OWNER = "yege168168"
GITHUB_REPO = "zuye"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://zuye-cqp.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://zuye-cqp.pages.dev/"

